-- ============================================================
--  NIGHTINGALE — 05 · Reference seed data
--  Run AFTER 04_security_users.sql.
--
--  Inserts the lookup data the system always needs:
--    • 5 departments
--    • 12 medicines (full clinic catalog)
--    • 1 default admin account
--    • 3 nurse accounts
--
--  Employees and patient accounts are seeded by 06_seed_5_years.sql
--  (generated by tools/generate_seed_5y.php).
--
--  ALL DEFAULT PASSWORDS in this file evaluate to "password"
--  (bcrypt hash: $2y$12$tL6xGk2/Iit2SSQZVuvDJejHH64K5D7dthslXi8b/UZuTeP8oz75O).
--  *** CHANGE EVERY PASSWORD BEFORE PRODUCTION DEPLOYMENT ***
-- ============================================================

USE nightingale_cms;

-- We bypass the audit triggers for reference data — there is no
-- acting user yet at install time.
SET @current_user_id  = NULL;
SET @current_admin_id = NULL;

-- ───────────────────────────── departments
INSERT INTO department (dept_id, dept_name) VALUES
  (1, 'Information Technology'),
  (2, 'Accounting'),
  (3, 'Operations'),
  (4, 'Human Resources'),
  (5, 'Administration & Executive');

-- ───────────────────────────── medicines (clinic catalog)
INSERT INTO medicine
  (medicine_id, medicine_name, generic_name, dosage_strength, unit, category,
   min_stock, current_stock, expiry_date)
VALUES
  ( 1, 'Biogesic',         'Paracetamol',        '500mg', 'tablet',  'Analgesic',                       80, 320, '2027-12-31'),
  ( 2, 'Ventolin',          'Salbutamol',         '2mg',   'tablet',  'Bronchodilator',                  40, 120, '2027-08-31'),
  ( 3, 'Amoxicillin',       'Amoxicillin',        '500mg', 'capsule', 'Antibiotic',                      40, 200, '2027-05-31'),
  ( 4, 'Cetirizine',        'Cetirizine',         '10mg',  'tablet',  'Antihistamine',                   40, 180, '2028-03-31'),
  ( 5, 'Omeprazole',        'Omeprazole',         '20mg',  'capsule', 'Antacid',                         30, 150, '2028-01-31'),
  ( 6, 'Mefenamic Acid',    'Mefenamic Acid',     '500mg', 'capsule', 'Analgesic/Anti-inflammatory',     40, 180, '2027-10-31'),
  ( 7, 'Losartan',          'Losartan',           '50mg',  'tablet',  'Antihypertensive',                30, 150, '2028-02-28'),
  ( 8, 'Metformin',         'Metformin',          '500mg', 'tablet',  'Antidiabetic',                    30, 130, '2027-11-30'),
  ( 9, 'Alcohol 70%',       'Isopropyl Alcohol',  '70%',   'bottle',  'Antiseptic',                      10,  40, '2027-09-30'),
  (10, 'Betadine',          'Povidone-Iodine',    '10%',   'bottle',  'Antiseptic',                      10,  35, '2028-01-31'),
  (11, 'Loperamide',        'Loperamide',         '2mg',   'capsule', 'Antidiarrheal',                   25,  90, '2027-07-31'),
  (12, 'Hyoscine',          'Hyoscine N-Butyl',   '10mg',  'tablet',  'Antispasmodic',                   25,  80, '2027-06-30');

-- ───────────────────────────── default admin
-- username:  admin           password: password
-- username:  hr.admin        password: password
INSERT INTO admin_account
  (admin_id, username, email, full_name, password_hash, totp_enabled, is_active)
VALUES
  (1, 'admin',    'admin@nightingale.clinic',
   'System Administrator',
   '$2y$12$tL6xGk2/Iit2SSQZVuvDJejHH64K5D7dthslXi8b/UZuTeP8oz75O',
   0, 1),
  (2, 'hr.admin', 'hr@nightingale.clinic',
   'Eleanor Garcia',
   '$2y$12$tL6xGk2/Iit2SSQZVuvDJejHH64K5D7dthslXi8b/UZuTeP8oz75O',
   0, 1);

-- ───────────────────────────── nurses
-- Nurses must exist BEFORE 5-year seed because every consultation
-- references a nurse_id.  The seed script keeps these IDs fixed.

INSERT INTO employee
  (employee_id, employee_no, first_name, last_name, birthdate, gender,
   blood_type, allergies, emergency_contact, emergency_phone, dept_id, hire_date)
VALUES
  (1, 'EMP-N0001', 'Ana',     'Reyes',  '1988-03-15', 'F', 'A+',  NULL, 'Juan Reyes',     '0917-111-0001', 4, '2018-04-02'),
  (2, 'EMP-N0002', 'Bea',     'Lim',    '1991-07-22', 'F', 'B+',  NULL, 'Roberto Lim',    '0917-111-0002', 4, '2019-09-15'),
  (3, 'EMP-N0003', 'Carmela', 'Cruz',   '1985-11-04', 'F', 'O+',  NULL, 'Jose Cruz',      '0917-111-0003', 4, '2017-01-09');

-- usernames:  nurse / blim / ccruz   passwords: password
INSERT INTO user_account
  (user_id, employee_id, username, email, password_hash, role, totp_enabled, is_active)
VALUES
  (1, 1, 'nurse', 'ana.reyes@nightingale.clinic',
   '$2y$12$tL6xGk2/Iit2SSQZVuvDJejHH64K5D7dthslXi8b/UZuTeP8oz75O', 'nurse', 0, 1),
  (2, 2, 'blim',  'bea.lim@nightingale.clinic',
   '$2y$12$tL6xGk2/Iit2SSQZVuvDJejHH64K5D7dthslXi8b/UZuTeP8oz75O', 'nurse', 0, 1),
  (3, 3, 'ccruz', 'carmela.cruz@nightingale.clinic',
   '$2y$12$tL6xGk2/Iit2SSQZVuvDJejHH64K5D7dthslXi8b/UZuTeP8oz75O', 'nurse', 0, 1);

INSERT INTO nurse_profile
  (nurse_id, user_id, license_no, license_expiry, specialization)
VALUES
  (1, 1, 'RN-09124', '2027-06-30', 'Occupational Health Nurse'),
  (2, 2, 'RN-11587', '2026-11-30', 'First-Aid & Emergency'),
  (3, 3, 'RN-08810', '2028-02-28', 'Public Health');

-- Make sure AUTO_INCREMENT counters resume above the seeded IDs.
ALTER TABLE department      AUTO_INCREMENT = 6;
ALTER TABLE medicine        AUTO_INCREMENT = 13;
ALTER TABLE admin_account   AUTO_INCREMENT = 3;
ALTER TABLE employee        AUTO_INCREMENT = 4;
ALTER TABLE user_account    AUTO_INCREMENT = 4;
ALTER TABLE nurse_profile   AUTO_INCREMENT = 4;
